// constants.js

const EMPTY_TILE = 0;
const TILE_OCCUPIED = 100;
const TREE_ON_TILE = 100;
const BENCH_ON_TILE = 150;
const BENCH_ON_TILE_SITTING = 250;
const FENCE_ON_TILE = 160;

export default { EMPTY_TILE, TILE_OCCUPIED, TREE_ON_TILE, BENCH_ON_TILE, BENCH_ON_TILE_SITTING, FENCE_ON_TILE };